#!/usr/bin/with-contenv bash

# initialise database
cd /app/fuseai
npx prisma migrate deploy &>/dev/null

# permissions
find /app/fuseai -path "*/node_modules" -prune -o -exec chown abc:abc {} +
chown -R abc:abc \
    /config \
    /root
