#!/usr/bin/with-contenv bash

VARIABLES=("NEXTAUTH_SECRET" "NEXTAUTH_URL" "ADMIN_EMAIL" "ADMIN_PASSWORD")
MESSAGES=("No JWT Secret has been specified in the NEXTAUTH_SECRET variable."
"No NextAuth URL has been specified in the NEXTAUTH_URL variable."
"No Admin Email address has been specified in the ADMIN_EMAIL variable."
"No Admin Password has been specified in the ADMIN_PASSWORD variable.")

if [[ -z "${TEST_RUN}" ]]; then
    for i in ${!VARIABLES[@]}; do
        if [ -z "${!VARIABLES[$i]}" ]; then
            echo "Error: ${MESSAGES[$i]}"
            echo "See the readme for more information: https://github.com/imagegenius/docker-ai-chat-app#variables"
            sleep infinity
        fi
    done
fi
