#!/usr/bin/with-contenv bash

check_var() {
    if [ -z "${!1}" ]; then
        echo "Error: No ${2} has been specified in the '${1}' variable. ${3}"
        echo "For more information, see the README: https://github.com/imagegenius/docker-ai-chat-app#variables"
        sleep infinity
    fi
}

#         Variable          Variable Summary
check_var "NEXTAUTH_SECRET" "JWT secret"
check_var "NEXTAUTH_URL"    "NextAuth URL"
check_var "ADMIN_EMAIL"     "admin email"
check_var "ADMIN_PASSWORD"  "admin password"
