name: Package Trigger Scheduler

on:
  schedule:
    - cron:  '38 2 * * 4'
  workflow_dispatch:

jobs:
  package-trigger-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: '0'

      - name: Package Trigger Scheduler
        run: |
          echo "**** Branches found: ****"
          git for-each-ref --format='%(refname:short)' refs/remotes
          for br in $(git for-each-ref --format='%(refname:short)' refs/remotes)
          do
            br=$(echo "$br" | sed 's|origin/||g')
            echo "**** Evaluating branch ${br} ****"
            ig_branch=$(curl -u ${{ secrets.CR_USER }}:${{ secrets.CR_PAT }} -sX GET https://raw.githubusercontent.com/imagegenius/docker-ai-chat-app/${br}/jenkins-vars.yml | yq -r '.ig_branch')
            if [ "${br}" == "${ig_branch}" ]; then
              echo "**** Branch ${br} appears to be live; checking workflow. ****"
              if curl -u ${{ secrets.CR_USER }}:${{ secrets.CR_PAT }} -sfX GET https://raw.githubusercontent.com/imagegenius/docker-ai-chat-app/${br}/.github/workflows/package_trigger.yml > /dev/null 2>&1; then
                echo "**** Workflow exists. Triggering package trigger workflow for branch ${br}. ****"
                echo "Triggering package trigger workflow for branch ${br}" >> $GITHUB_STEP_SUMMARY
                triggered_branches="${triggered_branches}${br} "
                curl -iX POST \
                  -H "Authorization: token ${{ secrets.CR_PAT }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -d "{\"ref\":\"refs/heads/${br}\"}" \
                  https://api.github.com/repos/imagegenius/docker-ai-chat-app/actions/workflows/package_trigger.yml/dispatches
                sleep 30
              else
                echo "**** Workflow doesn't exist; skipping trigger. ****"
                echo "Skipping branch ${br} due to no package trigger workflow present." >> $GITHUB_STEP_SUMMARY
              fi
            else
              echo "**** ${br} appears to be a dev branch; skipping trigger. ****"
              echo "Skipping branch ${br} due to being detected as dev branch." >> $GITHUB_STEP_SUMMARY
            fi
          done
          echo "**** Package check triggered for branches: ${triggered_branches} ****"
          echo "**** Notifying Discord ****"
          curl -X POST -H "Content-Type: application/json" --data '{"avatar_url": "https://cdn.discordapp.com/avatars/354986384542662657/df91181b3f1cf0ef1592fbe18e0962d7.png","embeds": [{"color": 9802903,
            "description": "**Package Check Triggered for ai-chat-app** \n**Branches:** '"${triggered_branches}"' \n**Build URL:** '"https://ci.imagegenius.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-ai-chat-app/activity/"' \n"}],
            "username": "Github Actions"}' ${{ secrets.DISCORD_WEBHOOK }}
